// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ernado/tentacle/internal/ent/predicate"
	"github.com/ernado/tentacle/internal/ent/telegramblob"
	"github.com/ernado/tentacle/internal/ent/telegramchannel"
	"github.com/ernado/tentacle/internal/ent/telegramsession"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTelegramBlob    = "TelegramBlob"
	TypeTelegramChannel = "TelegramChannel"
	TypeTelegramSession = "TelegramSession"
)

// TelegramBlobMutation represents an operation that mutates the TelegramBlob nodes in the graph.
type TelegramBlobMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	size           *int64
	addsize        *int64
	_path          *string
	uri            *string
	sha256         *string
	file_reference *[]byte
	file_id        *int64
	addfile_id     *int64
	access_hash    *int64
	addaccess_hash *int64
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*TelegramBlob, error)
	predicates     []predicate.TelegramBlob
}

var _ ent.Mutation = (*TelegramBlobMutation)(nil)

// telegramblobOption allows management of the mutation configuration using functional options.
type telegramblobOption func(*TelegramBlobMutation)

// newTelegramBlobMutation creates new mutation for the TelegramBlob entity.
func newTelegramBlobMutation(c config, op Op, opts ...telegramblobOption) *TelegramBlobMutation {
	m := &TelegramBlobMutation{
		config:        c,
		op:            op,
		typ:           TypeTelegramBlob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTelegramBlobID sets the ID field of the mutation.
func withTelegramBlobID(id uuid.UUID) telegramblobOption {
	return func(m *TelegramBlobMutation) {
		var (
			err   error
			once  sync.Once
			value *TelegramBlob
		)
		m.oldValue = func(ctx context.Context) (*TelegramBlob, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TelegramBlob.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTelegramBlob sets the old TelegramBlob of the mutation.
func withTelegramBlob(node *TelegramBlob) telegramblobOption {
	return func(m *TelegramBlobMutation) {
		m.oldValue = func(context.Context) (*TelegramBlob, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TelegramBlobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TelegramBlobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TelegramBlob entities.
func (m *TelegramBlobMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TelegramBlobMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TelegramBlobMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TelegramBlob.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSize sets the "size" field.
func (m *TelegramBlobMutation) SetSize(i int64) {
	m.size = &i
	m.addsize = nil
}

// Size returns the value of the "size" field in the mutation.
func (m *TelegramBlobMutation) Size() (r int64, exists bool) {
	v := m.size
	if v == nil {
		return
	}
	return *v, true
}

// OldSize returns the old "size" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldSize(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSize is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSize requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSize: %w", err)
	}
	return oldValue.Size, nil
}

// AddSize adds i to the "size" field.
func (m *TelegramBlobMutation) AddSize(i int64) {
	if m.addsize != nil {
		*m.addsize += i
	} else {
		m.addsize = &i
	}
}

// AddedSize returns the value that was added to the "size" field in this mutation.
func (m *TelegramBlobMutation) AddedSize() (r int64, exists bool) {
	v := m.addsize
	if v == nil {
		return
	}
	return *v, true
}

// ResetSize resets all changes to the "size" field.
func (m *TelegramBlobMutation) ResetSize() {
	m.size = nil
	m.addsize = nil
}

// SetPath sets the "path" field.
func (m *TelegramBlobMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *TelegramBlobMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *TelegramBlobMutation) ResetPath() {
	m._path = nil
}

// SetURI sets the "uri" field.
func (m *TelegramBlobMutation) SetURI(s string) {
	m.uri = &s
}

// URI returns the value of the "uri" field in the mutation.
func (m *TelegramBlobMutation) URI() (r string, exists bool) {
	v := m.uri
	if v == nil {
		return
	}
	return *v, true
}

// OldURI returns the old "uri" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldURI(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURI is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURI requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURI: %w", err)
	}
	return oldValue.URI, nil
}

// ResetURI resets all changes to the "uri" field.
func (m *TelegramBlobMutation) ResetURI() {
	m.uri = nil
}

// SetSha256 sets the "sha256" field.
func (m *TelegramBlobMutation) SetSha256(s string) {
	m.sha256 = &s
}

// Sha256 returns the value of the "sha256" field in the mutation.
func (m *TelegramBlobMutation) Sha256() (r string, exists bool) {
	v := m.sha256
	if v == nil {
		return
	}
	return *v, true
}

// OldSha256 returns the old "sha256" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldSha256(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSha256 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSha256 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSha256: %w", err)
	}
	return oldValue.Sha256, nil
}

// ResetSha256 resets all changes to the "sha256" field.
func (m *TelegramBlobMutation) ResetSha256() {
	m.sha256 = nil
}

// SetFileReference sets the "file_reference" field.
func (m *TelegramBlobMutation) SetFileReference(b []byte) {
	m.file_reference = &b
}

// FileReference returns the value of the "file_reference" field in the mutation.
func (m *TelegramBlobMutation) FileReference() (r []byte, exists bool) {
	v := m.file_reference
	if v == nil {
		return
	}
	return *v, true
}

// OldFileReference returns the old "file_reference" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldFileReference(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFileReference is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFileReference requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFileReference: %w", err)
	}
	return oldValue.FileReference, nil
}

// ResetFileReference resets all changes to the "file_reference" field.
func (m *TelegramBlobMutation) ResetFileReference() {
	m.file_reference = nil
}

// SetFileID sets the "file_id" field.
func (m *TelegramBlobMutation) SetFileID(i int64) {
	m.file_id = &i
	m.addfile_id = nil
}

// FileID returns the value of the "file_id" field in the mutation.
func (m *TelegramBlobMutation) FileID() (r int64, exists bool) {
	v := m.file_id
	if v == nil {
		return
	}
	return *v, true
}

// OldFileID returns the old "file_id" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldFileID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFileID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFileID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFileID: %w", err)
	}
	return oldValue.FileID, nil
}

// AddFileID adds i to the "file_id" field.
func (m *TelegramBlobMutation) AddFileID(i int64) {
	if m.addfile_id != nil {
		*m.addfile_id += i
	} else {
		m.addfile_id = &i
	}
}

// AddedFileID returns the value that was added to the "file_id" field in this mutation.
func (m *TelegramBlobMutation) AddedFileID() (r int64, exists bool) {
	v := m.addfile_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetFileID resets all changes to the "file_id" field.
func (m *TelegramBlobMutation) ResetFileID() {
	m.file_id = nil
	m.addfile_id = nil
}

// SetAccessHash sets the "access_hash" field.
func (m *TelegramBlobMutation) SetAccessHash(i int64) {
	m.access_hash = &i
	m.addaccess_hash = nil
}

// AccessHash returns the value of the "access_hash" field in the mutation.
func (m *TelegramBlobMutation) AccessHash() (r int64, exists bool) {
	v := m.access_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessHash returns the old "access_hash" field's value of the TelegramBlob entity.
// If the TelegramBlob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramBlobMutation) OldAccessHash(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessHash: %w", err)
	}
	return oldValue.AccessHash, nil
}

// AddAccessHash adds i to the "access_hash" field.
func (m *TelegramBlobMutation) AddAccessHash(i int64) {
	if m.addaccess_hash != nil {
		*m.addaccess_hash += i
	} else {
		m.addaccess_hash = &i
	}
}

// AddedAccessHash returns the value that was added to the "access_hash" field in this mutation.
func (m *TelegramBlobMutation) AddedAccessHash() (r int64, exists bool) {
	v := m.addaccess_hash
	if v == nil {
		return
	}
	return *v, true
}

// ResetAccessHash resets all changes to the "access_hash" field.
func (m *TelegramBlobMutation) ResetAccessHash() {
	m.access_hash = nil
	m.addaccess_hash = nil
}

// Where appends a list predicates to the TelegramBlobMutation builder.
func (m *TelegramBlobMutation) Where(ps ...predicate.TelegramBlob) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TelegramBlobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TelegramBlobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TelegramBlob, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TelegramBlobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TelegramBlobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TelegramBlob).
func (m *TelegramBlobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TelegramBlobMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.size != nil {
		fields = append(fields, telegramblob.FieldSize)
	}
	if m._path != nil {
		fields = append(fields, telegramblob.FieldPath)
	}
	if m.uri != nil {
		fields = append(fields, telegramblob.FieldURI)
	}
	if m.sha256 != nil {
		fields = append(fields, telegramblob.FieldSha256)
	}
	if m.file_reference != nil {
		fields = append(fields, telegramblob.FieldFileReference)
	}
	if m.file_id != nil {
		fields = append(fields, telegramblob.FieldFileID)
	}
	if m.access_hash != nil {
		fields = append(fields, telegramblob.FieldAccessHash)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TelegramBlobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case telegramblob.FieldSize:
		return m.Size()
	case telegramblob.FieldPath:
		return m.Path()
	case telegramblob.FieldURI:
		return m.URI()
	case telegramblob.FieldSha256:
		return m.Sha256()
	case telegramblob.FieldFileReference:
		return m.FileReference()
	case telegramblob.FieldFileID:
		return m.FileID()
	case telegramblob.FieldAccessHash:
		return m.AccessHash()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TelegramBlobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case telegramblob.FieldSize:
		return m.OldSize(ctx)
	case telegramblob.FieldPath:
		return m.OldPath(ctx)
	case telegramblob.FieldURI:
		return m.OldURI(ctx)
	case telegramblob.FieldSha256:
		return m.OldSha256(ctx)
	case telegramblob.FieldFileReference:
		return m.OldFileReference(ctx)
	case telegramblob.FieldFileID:
		return m.OldFileID(ctx)
	case telegramblob.FieldAccessHash:
		return m.OldAccessHash(ctx)
	}
	return nil, fmt.Errorf("unknown TelegramBlob field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramBlobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case telegramblob.FieldSize:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSize(v)
		return nil
	case telegramblob.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case telegramblob.FieldURI:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURI(v)
		return nil
	case telegramblob.FieldSha256:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSha256(v)
		return nil
	case telegramblob.FieldFileReference:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFileReference(v)
		return nil
	case telegramblob.FieldFileID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFileID(v)
		return nil
	case telegramblob.FieldAccessHash:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessHash(v)
		return nil
	}
	return fmt.Errorf("unknown TelegramBlob field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TelegramBlobMutation) AddedFields() []string {
	var fields []string
	if m.addsize != nil {
		fields = append(fields, telegramblob.FieldSize)
	}
	if m.addfile_id != nil {
		fields = append(fields, telegramblob.FieldFileID)
	}
	if m.addaccess_hash != nil {
		fields = append(fields, telegramblob.FieldAccessHash)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TelegramBlobMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case telegramblob.FieldSize:
		return m.AddedSize()
	case telegramblob.FieldFileID:
		return m.AddedFileID()
	case telegramblob.FieldAccessHash:
		return m.AddedAccessHash()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramBlobMutation) AddField(name string, value ent.Value) error {
	switch name {
	case telegramblob.FieldSize:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSize(v)
		return nil
	case telegramblob.FieldFileID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFileID(v)
		return nil
	case telegramblob.FieldAccessHash:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccessHash(v)
		return nil
	}
	return fmt.Errorf("unknown TelegramBlob numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TelegramBlobMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TelegramBlobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TelegramBlobMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TelegramBlob nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TelegramBlobMutation) ResetField(name string) error {
	switch name {
	case telegramblob.FieldSize:
		m.ResetSize()
		return nil
	case telegramblob.FieldPath:
		m.ResetPath()
		return nil
	case telegramblob.FieldURI:
		m.ResetURI()
		return nil
	case telegramblob.FieldSha256:
		m.ResetSha256()
		return nil
	case telegramblob.FieldFileReference:
		m.ResetFileReference()
		return nil
	case telegramblob.FieldFileID:
		m.ResetFileID()
		return nil
	case telegramblob.FieldAccessHash:
		m.ResetAccessHash()
		return nil
	}
	return fmt.Errorf("unknown TelegramBlob field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TelegramBlobMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TelegramBlobMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TelegramBlobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TelegramBlobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TelegramBlobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TelegramBlobMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TelegramBlobMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TelegramBlob unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TelegramBlobMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TelegramBlob edge %s", name)
}

// TelegramChannelMutation represents an operation that mutates the TelegramChannel nodes in the graph.
type TelegramChannelMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int64
	access_hash           *int64
	addaccess_hash        *int64
	title                 *string
	save_records          *bool
	save_favorite_records *bool
	active                *bool
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*TelegramChannel, error)
	predicates            []predicate.TelegramChannel
}

var _ ent.Mutation = (*TelegramChannelMutation)(nil)

// telegramchannelOption allows management of the mutation configuration using functional options.
type telegramchannelOption func(*TelegramChannelMutation)

// newTelegramChannelMutation creates new mutation for the TelegramChannel entity.
func newTelegramChannelMutation(c config, op Op, opts ...telegramchannelOption) *TelegramChannelMutation {
	m := &TelegramChannelMutation{
		config:        c,
		op:            op,
		typ:           TypeTelegramChannel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTelegramChannelID sets the ID field of the mutation.
func withTelegramChannelID(id int64) telegramchannelOption {
	return func(m *TelegramChannelMutation) {
		var (
			err   error
			once  sync.Once
			value *TelegramChannel
		)
		m.oldValue = func(ctx context.Context) (*TelegramChannel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TelegramChannel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTelegramChannel sets the old TelegramChannel of the mutation.
func withTelegramChannel(node *TelegramChannel) telegramchannelOption {
	return func(m *TelegramChannelMutation) {
		m.oldValue = func(context.Context) (*TelegramChannel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TelegramChannelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TelegramChannelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TelegramChannel entities.
func (m *TelegramChannelMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TelegramChannelMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TelegramChannelMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TelegramChannel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAccessHash sets the "access_hash" field.
func (m *TelegramChannelMutation) SetAccessHash(i int64) {
	m.access_hash = &i
	m.addaccess_hash = nil
}

// AccessHash returns the value of the "access_hash" field in the mutation.
func (m *TelegramChannelMutation) AccessHash() (r int64, exists bool) {
	v := m.access_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessHash returns the old "access_hash" field's value of the TelegramChannel entity.
// If the TelegramChannel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramChannelMutation) OldAccessHash(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessHash: %w", err)
	}
	return oldValue.AccessHash, nil
}

// AddAccessHash adds i to the "access_hash" field.
func (m *TelegramChannelMutation) AddAccessHash(i int64) {
	if m.addaccess_hash != nil {
		*m.addaccess_hash += i
	} else {
		m.addaccess_hash = &i
	}
}

// AddedAccessHash returns the value that was added to the "access_hash" field in this mutation.
func (m *TelegramChannelMutation) AddedAccessHash() (r int64, exists bool) {
	v := m.addaccess_hash
	if v == nil {
		return
	}
	return *v, true
}

// ResetAccessHash resets all changes to the "access_hash" field.
func (m *TelegramChannelMutation) ResetAccessHash() {
	m.access_hash = nil
	m.addaccess_hash = nil
}

// SetTitle sets the "title" field.
func (m *TelegramChannelMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *TelegramChannelMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the TelegramChannel entity.
// If the TelegramChannel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramChannelMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *TelegramChannelMutation) ResetTitle() {
	m.title = nil
}

// SetSaveRecords sets the "save_records" field.
func (m *TelegramChannelMutation) SetSaveRecords(b bool) {
	m.save_records = &b
}

// SaveRecords returns the value of the "save_records" field in the mutation.
func (m *TelegramChannelMutation) SaveRecords() (r bool, exists bool) {
	v := m.save_records
	if v == nil {
		return
	}
	return *v, true
}

// OldSaveRecords returns the old "save_records" field's value of the TelegramChannel entity.
// If the TelegramChannel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramChannelMutation) OldSaveRecords(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSaveRecords is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSaveRecords requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSaveRecords: %w", err)
	}
	return oldValue.SaveRecords, nil
}

// ClearSaveRecords clears the value of the "save_records" field.
func (m *TelegramChannelMutation) ClearSaveRecords() {
	m.save_records = nil
	m.clearedFields[telegramchannel.FieldSaveRecords] = struct{}{}
}

// SaveRecordsCleared returns if the "save_records" field was cleared in this mutation.
func (m *TelegramChannelMutation) SaveRecordsCleared() bool {
	_, ok := m.clearedFields[telegramchannel.FieldSaveRecords]
	return ok
}

// ResetSaveRecords resets all changes to the "save_records" field.
func (m *TelegramChannelMutation) ResetSaveRecords() {
	m.save_records = nil
	delete(m.clearedFields, telegramchannel.FieldSaveRecords)
}

// SetSaveFavoriteRecords sets the "save_favorite_records" field.
func (m *TelegramChannelMutation) SetSaveFavoriteRecords(b bool) {
	m.save_favorite_records = &b
}

// SaveFavoriteRecords returns the value of the "save_favorite_records" field in the mutation.
func (m *TelegramChannelMutation) SaveFavoriteRecords() (r bool, exists bool) {
	v := m.save_favorite_records
	if v == nil {
		return
	}
	return *v, true
}

// OldSaveFavoriteRecords returns the old "save_favorite_records" field's value of the TelegramChannel entity.
// If the TelegramChannel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramChannelMutation) OldSaveFavoriteRecords(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSaveFavoriteRecords is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSaveFavoriteRecords requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSaveFavoriteRecords: %w", err)
	}
	return oldValue.SaveFavoriteRecords, nil
}

// ClearSaveFavoriteRecords clears the value of the "save_favorite_records" field.
func (m *TelegramChannelMutation) ClearSaveFavoriteRecords() {
	m.save_favorite_records = nil
	m.clearedFields[telegramchannel.FieldSaveFavoriteRecords] = struct{}{}
}

// SaveFavoriteRecordsCleared returns if the "save_favorite_records" field was cleared in this mutation.
func (m *TelegramChannelMutation) SaveFavoriteRecordsCleared() bool {
	_, ok := m.clearedFields[telegramchannel.FieldSaveFavoriteRecords]
	return ok
}

// ResetSaveFavoriteRecords resets all changes to the "save_favorite_records" field.
func (m *TelegramChannelMutation) ResetSaveFavoriteRecords() {
	m.save_favorite_records = nil
	delete(m.clearedFields, telegramchannel.FieldSaveFavoriteRecords)
}

// SetActive sets the "active" field.
func (m *TelegramChannelMutation) SetActive(b bool) {
	m.active = &b
}

// Active returns the value of the "active" field in the mutation.
func (m *TelegramChannelMutation) Active() (r bool, exists bool) {
	v := m.active
	if v == nil {
		return
	}
	return *v, true
}

// OldActive returns the old "active" field's value of the TelegramChannel entity.
// If the TelegramChannel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramChannelMutation) OldActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActive: %w", err)
	}
	return oldValue.Active, nil
}

// ResetActive resets all changes to the "active" field.
func (m *TelegramChannelMutation) ResetActive() {
	m.active = nil
}

// Where appends a list predicates to the TelegramChannelMutation builder.
func (m *TelegramChannelMutation) Where(ps ...predicate.TelegramChannel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TelegramChannelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TelegramChannelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TelegramChannel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TelegramChannelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TelegramChannelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TelegramChannel).
func (m *TelegramChannelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TelegramChannelMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.access_hash != nil {
		fields = append(fields, telegramchannel.FieldAccessHash)
	}
	if m.title != nil {
		fields = append(fields, telegramchannel.FieldTitle)
	}
	if m.save_records != nil {
		fields = append(fields, telegramchannel.FieldSaveRecords)
	}
	if m.save_favorite_records != nil {
		fields = append(fields, telegramchannel.FieldSaveFavoriteRecords)
	}
	if m.active != nil {
		fields = append(fields, telegramchannel.FieldActive)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TelegramChannelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case telegramchannel.FieldAccessHash:
		return m.AccessHash()
	case telegramchannel.FieldTitle:
		return m.Title()
	case telegramchannel.FieldSaveRecords:
		return m.SaveRecords()
	case telegramchannel.FieldSaveFavoriteRecords:
		return m.SaveFavoriteRecords()
	case telegramchannel.FieldActive:
		return m.Active()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TelegramChannelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case telegramchannel.FieldAccessHash:
		return m.OldAccessHash(ctx)
	case telegramchannel.FieldTitle:
		return m.OldTitle(ctx)
	case telegramchannel.FieldSaveRecords:
		return m.OldSaveRecords(ctx)
	case telegramchannel.FieldSaveFavoriteRecords:
		return m.OldSaveFavoriteRecords(ctx)
	case telegramchannel.FieldActive:
		return m.OldActive(ctx)
	}
	return nil, fmt.Errorf("unknown TelegramChannel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramChannelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case telegramchannel.FieldAccessHash:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessHash(v)
		return nil
	case telegramchannel.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case telegramchannel.FieldSaveRecords:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSaveRecords(v)
		return nil
	case telegramchannel.FieldSaveFavoriteRecords:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSaveFavoriteRecords(v)
		return nil
	case telegramchannel.FieldActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActive(v)
		return nil
	}
	return fmt.Errorf("unknown TelegramChannel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TelegramChannelMutation) AddedFields() []string {
	var fields []string
	if m.addaccess_hash != nil {
		fields = append(fields, telegramchannel.FieldAccessHash)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TelegramChannelMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case telegramchannel.FieldAccessHash:
		return m.AddedAccessHash()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramChannelMutation) AddField(name string, value ent.Value) error {
	switch name {
	case telegramchannel.FieldAccessHash:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccessHash(v)
		return nil
	}
	return fmt.Errorf("unknown TelegramChannel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TelegramChannelMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(telegramchannel.FieldSaveRecords) {
		fields = append(fields, telegramchannel.FieldSaveRecords)
	}
	if m.FieldCleared(telegramchannel.FieldSaveFavoriteRecords) {
		fields = append(fields, telegramchannel.FieldSaveFavoriteRecords)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TelegramChannelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TelegramChannelMutation) ClearField(name string) error {
	switch name {
	case telegramchannel.FieldSaveRecords:
		m.ClearSaveRecords()
		return nil
	case telegramchannel.FieldSaveFavoriteRecords:
		m.ClearSaveFavoriteRecords()
		return nil
	}
	return fmt.Errorf("unknown TelegramChannel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TelegramChannelMutation) ResetField(name string) error {
	switch name {
	case telegramchannel.FieldAccessHash:
		m.ResetAccessHash()
		return nil
	case telegramchannel.FieldTitle:
		m.ResetTitle()
		return nil
	case telegramchannel.FieldSaveRecords:
		m.ResetSaveRecords()
		return nil
	case telegramchannel.FieldSaveFavoriteRecords:
		m.ResetSaveFavoriteRecords()
		return nil
	case telegramchannel.FieldActive:
		m.ResetActive()
		return nil
	}
	return fmt.Errorf("unknown TelegramChannel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TelegramChannelMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TelegramChannelMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TelegramChannelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TelegramChannelMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TelegramChannelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TelegramChannelMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TelegramChannelMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TelegramChannel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TelegramChannelMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TelegramChannel edge %s", name)
}

// TelegramSessionMutation represents an operation that mutates the TelegramSession nodes in the graph.
type TelegramSessionMutation struct {
	config
	op            Op
	typ           string
	id            *int
	data          *[]byte
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TelegramSession, error)
	predicates    []predicate.TelegramSession
}

var _ ent.Mutation = (*TelegramSessionMutation)(nil)

// telegramsessionOption allows management of the mutation configuration using functional options.
type telegramsessionOption func(*TelegramSessionMutation)

// newTelegramSessionMutation creates new mutation for the TelegramSession entity.
func newTelegramSessionMutation(c config, op Op, opts ...telegramsessionOption) *TelegramSessionMutation {
	m := &TelegramSessionMutation{
		config:        c,
		op:            op,
		typ:           TypeTelegramSession,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTelegramSessionID sets the ID field of the mutation.
func withTelegramSessionID(id int) telegramsessionOption {
	return func(m *TelegramSessionMutation) {
		var (
			err   error
			once  sync.Once
			value *TelegramSession
		)
		m.oldValue = func(ctx context.Context) (*TelegramSession, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TelegramSession.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTelegramSession sets the old TelegramSession of the mutation.
func withTelegramSession(node *TelegramSession) telegramsessionOption {
	return func(m *TelegramSessionMutation) {
		m.oldValue = func(context.Context) (*TelegramSession, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TelegramSessionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TelegramSessionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TelegramSession entities.
func (m *TelegramSessionMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TelegramSessionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TelegramSessionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TelegramSession.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetData sets the "data" field.
func (m *TelegramSessionMutation) SetData(b []byte) {
	m.data = &b
}

// Data returns the value of the "data" field in the mutation.
func (m *TelegramSessionMutation) Data() (r []byte, exists bool) {
	v := m.data
	if v == nil {
		return
	}
	return *v, true
}

// OldData returns the old "data" field's value of the TelegramSession entity.
// If the TelegramSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TelegramSessionMutation) OldData(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldData: %w", err)
	}
	return oldValue.Data, nil
}

// ResetData resets all changes to the "data" field.
func (m *TelegramSessionMutation) ResetData() {
	m.data = nil
}

// Where appends a list predicates to the TelegramSessionMutation builder.
func (m *TelegramSessionMutation) Where(ps ...predicate.TelegramSession) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TelegramSessionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TelegramSessionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TelegramSession, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TelegramSessionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TelegramSessionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TelegramSession).
func (m *TelegramSessionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TelegramSessionMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.data != nil {
		fields = append(fields, telegramsession.FieldData)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TelegramSessionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case telegramsession.FieldData:
		return m.Data()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TelegramSessionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case telegramsession.FieldData:
		return m.OldData(ctx)
	}
	return nil, fmt.Errorf("unknown TelegramSession field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramSessionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case telegramsession.FieldData:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetData(v)
		return nil
	}
	return fmt.Errorf("unknown TelegramSession field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TelegramSessionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TelegramSessionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TelegramSessionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TelegramSession numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TelegramSessionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TelegramSessionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TelegramSessionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TelegramSession nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TelegramSessionMutation) ResetField(name string) error {
	switch name {
	case telegramsession.FieldData:
		m.ResetData()
		return nil
	}
	return fmt.Errorf("unknown TelegramSession field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TelegramSessionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TelegramSessionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TelegramSessionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TelegramSessionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TelegramSessionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TelegramSessionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TelegramSessionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TelegramSession unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TelegramSessionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TelegramSession edge %s", name)
}
