// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ernado/tentacle/internal/ent/schema"
	"github.com/ernado/tentacle/internal/ent/telegramblob"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	telegramblobFields := schema.TelegramBlob{}.Fields()
	_ = telegramblobFields
	// telegramblobDescID is the schema descriptor for id field.
	telegramblobDescID := telegramblobFields[0].Descriptor()
	// telegramblob.DefaultID holds the default value on creation for the id field.
	telegramblob.DefaultID = telegramblobDescID.Default.(func() uuid.UUID)
}
