// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ernado/tentacle/internal/ent/predicate"
	"github.com/ernado/tentacle/internal/ent/telegramchannel"
)

// TelegramChannelDelete is the builder for deleting a TelegramChannel entity.
type TelegramChannelDelete struct {
	config
	hooks    []Hook
	mutation *TelegramChannelMutation
}

// Where appends a list predicates to the TelegramChannelDelete builder.
func (_d *TelegramChannelDelete) Where(ps ...predicate.TelegramChannel) *TelegramChannelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TelegramChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TelegramChannelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TelegramChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(telegramchannel.Table, sqlgraph.NewFieldSpec(telegramchannel.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TelegramChannelDeleteOne is the builder for deleting a single TelegramChannel entity.
type TelegramChannelDeleteOne struct {
	_d *TelegramChannelDelete
}

// Where appends a list predicates to the TelegramChannelDelete builder.
func (_d *TelegramChannelDeleteOne) Where(ps ...predicate.TelegramChannel) *TelegramChannelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TelegramChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{telegramchannel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TelegramChannelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
