// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TelegramBlob is the predicate function for telegramblob builders.
type TelegramBlob func(*sql.Selector)

// TelegramChannel is the predicate function for telegramchannel builders.
type TelegramChannel func(*sql.Selector)

// TelegramSession is the predicate function for telegramsession builders.
type TelegramSession func(*sql.Selector)
