name: x

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  security-events: write
  contents: read

# Common Go workflows from go faster
# See https://github.com/go-faster/x
jobs:
  test:
    uses: go-faster/x/.github/workflows/test.yml@main
  lint:
    uses: go-faster/x/.github/workflows/lint.yml@main
  codeql:
    uses: go-faster/x/.github/workflows/codeql.yml@main
